### ISSUE TITLE
Add unit test framework

### ISSUE THREAD

**Issue by rehrumesh** [99xt/contributors-shield#15]

**Comment by Janakshi28** [comment]
Working on it and using Mocha as the testing library.

**Comment by dinukadesilva** [comment]
@Janakshi28 Since this is a react project, `jest` would be the ideal.

**Comment by Janakshi28** [comment]
@dinukadesilva its source code is written in NodeJs.

**Comment by rehrumesh** [comment]
@dinukadesilva This is not a react project.

**Comment by dinukadesilva** [comment]
a mistake @rehrumesh :)
